---
baseURL: '/'
languageCode: en-us
title: guide fari
theme: archie
copyright: © guide fari
# code highlight
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
paginate: 10
params:
  # mode can be auto or toggle
  mode: auto
  useCDN: false
  subtitle: 'software engineering, music, & everything between'
  social:
    - name: GitHub
      icon: github
      url: 'https://github.com/txndai'
    - name: LinkedIn
      icon: linkedin
      url: 'https://www.linkedin.com/in/guide-fari-8b0063176/'
    - name: Spotify
      icon: spotify
      url: 'https://www.linkedin.com/in/guide-fari-8b0063176/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
Permalinks:
  posts: '/:filename/'

...